title: Marcos Bressan
logo: "/images/photo.png"
description: >
  Senior Software & DevOps Engineer
  <br>
  <a href="https://www.linkedin.com/in/bressanmarcos/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-168058669-2 # your Google Analytics tracking ID here
