title: Marcos Bressan # your name (or website title) here
logo: "/images/photo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Electrical, Electronics and Computer Engineer
  <br><br>
  Passionate about Machine Learning and Distributed Computing
  <br><br>
  <a href="https://www.linkedin.com/in/bressanmarcos/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-168058669-2 # your Google Analytics tracking ID here
